server:
  port: 443
  ssl:
    enabled: true
    key-store: src/main/resources/fridge_chef_https.p12
    key-store-password: qwer1234
    key-store-type: PKCS12
    key-alias: fridge_https

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
    bean: jasyptStringEncryptor

spring:
  profiles:
    default: local
  output:
    ansi:
      enabled: always